{% set name = "profet" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - numpy
    - pypdb
    - requests
    - requests-html
    - pandas
    - bs4
  run:
    - python
    - numpy
    - pypdb
    - requests
    - requests-html
    - pandas
    - bs4

test:
  imports:
    - profet
  requires:
    - mock
    - pytest
    - pytest-cov

about:
  summary: "Download PDB files"
